/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.example.Perimetrable

class Coche(private var _marca: String = "FORD", private var _modelo:Int = 2020 ) {
    var marca: String
        get() = _marca
        set(value){
            _marca = value
        }
    var modelo: Int
        get() = _modelo
        set(value){
            _modelo = value
        }
}

interface Perimetrable {
    fun calcularPerimetro(): Double
}

class Rectangulo(val ancho: Double, val alto: Double) : Perimetrable {
    var area: Double

    // El bloque init se usa para inicializar propiedades o ejecutar código en la creación.
    init {
        // 'area' se calcula una vez cuando se crea el objeto.
        area = ancho * alto
        println("Se ha creado un rectángulo de $ancho x $alto con un área de $area")
    }

    // Un método de la clase
    fun describir() {
        println("Este es un rectángulo.")
    }

    // Un método que realiza un cálculo
    override fun calcularPerimetro(): Double {
        return 2 * (ancho + alto)
    }
}

class Circulo(val radio: Double) : Perimetrable{
    override fun calcularPerimetro() : Double{
        return 2 * 3.14 * radio
    }

}

fun main() {
    val coche = Coche("Chevron", 2022)

    println("Marca = ${coche.marca}")
    println("Modelo = ${coche.modelo}")

    var rectangulo = Rectangulo(10.0, 5.0)
    println("Area = ${rectangulo.area}")
    println("Perimetro = ${rectangulo.calcularPerimetro()}")

    var circulo = Circulo(3.0)

    val figuras: List<Perimetrable> = listOf(rectangulo, circulo)

    for (figura in figuras){
        println("La figura tiene este perimetro: ${figura.calcularPerimetro()}")
    }

}
